#!/usr/bin/env bash
# maker.sh — the MAKER step for this loop, generated by LoopPrint.
#
# Contract: produce exactly ONE change toward the goal, then exit.
#   exit 0  => a change was attempted (the runner will now call the EXTERNAL verifier)
#   exit !0 => the maker could not act this iteration (the runner logs it and still verifies)
#
# Hard rules (maker != checker):
#   * This is the MAKER ONLY. It must never grade its own work — that is verify.sh's job, run as a
#     SEPARATE process by the runner. Do not call verify.sh from here.
#   * This script never eval's a command string taken from loop-spec.yaml (see SECURITY.md). The wizard
#     pastes your harness's maker command below (from the profile's dispatch.maker); it is fixed text in
#     this file, not data read from the spec at runtime.
set -euo pipefail

GOAL="${GOAL:-<one-sentence goal>}"

# --- pick ONE dispatch for your harness; delete the rest -----------------------
# LoopPrint fills this from your profile's dispatch.maker (references/profiles.md). Keep it to ONE change
# per invocation so the verifier gates each step.
#
#   oh-my-claudecode:   claude -p "Make exactly one change toward: $GOAL. Then stop. Do not self-grade."
#   sub-agent dispatch: your-dispatch --role executor --once --task "$GOAL"
#   plain CLI / fixer:  your_tool --fix
#
echo "maker.sh: no maker dispatch wired in yet — edit this file (see references/profiles.md)." >&2
exit 1
