#!/usr/bin/env bash
# run-this-loop.sh — engine-agnostic loop runner generated by LoopPrint.
#
# Implements the four atoms literally:
#   Goal      — stated once in loop-spec.yaml; this runner does not re-derive it.
#   State     — appended to $STATE_FILE (human view) and $STATE_JSONL (append-only machine checkpoint) each iter.
#   Verifier  — $VERIFIER (default verify.sh), run as a SEPARATE process; exit 0 = GREEN. EXTERNAL by construction.
#   Stop      — whichever hits first: GREEN+accepted, $MAX_ITERS, or the HALT file.
#
# The MAKER is also a separate process ($MAKER, default maker.sh) — maker != checker, enforced structurally.
# This runner NEVER eval's a command string from the spec (see SECURITY.md): it execs sibling scripts only.
#
# Usage:
#   bash run-this-loop.sh            # run the loop
#   bash run-this-loop.sh --check    # preflight: confirm verify.sh + maker.sh are runnable; change nothing
#   bash run-this-loop.sh --resume   # continue the iteration count from $METRICS_FILE
set -euo pipefail

# ---- the four atoms (filled by LoopPrint from loop-spec.yaml) ----------------
GOAL="${GOAL:-<one-sentence goal>}"
STATE_FILE="${STATE_FILE:-state.md}"
STATE_JSONL="${STATE_JSONL:-state.jsonl}"      # append-only machine checkpoint (state.md is the human view)
VERIFIER="${VERIFIER:-verify.sh}"              # external gate: exits 0 = GREEN. Its own process.
MAKER="${MAKER:-maker.sh}"                      # the maker step: one change toward the goal. Its own process.
MAX_ITERS="${MAX_ITERS:-10}"
HALT_FILE="${HALT_FILE:-HALT}"
RUN_LOCK="${RUN_LOCK:-.running}"               # present only while this run is live; loopprint-ls uses it to tell
                                              # a live RED streak from a terminal one (don't false-report ROTTEN)
AUTONOMY="${AUTONOMY:-checkpoint}"             # full | checkpoint | dry-run
CHECKPOINT_MODE="${CHECKPOINT_MODE:-before}"   # before = authorize each iteration; after = review each result
METRICS_FILE="${METRICS_FILE:-metrics.jsonl}"  # append-only per-iteration metrics; feeds loopprint-report.py
METRICS_ADAPTER="${METRICS_ADAPTER:-}"         # optional cmd: prints "<tokens> <cost_usd>" for an iteration
                                               # (harness-specific). Core stays dep-free; tokens/cost are
                                               # INJECTED here, never parsed from the spec. Empty => null/null.
VERIFIER_SHAPE="${VERIFIER_SHAPE:-gate}"       # gate | ratchet. ratchet = "no worse than baseline": GREEN != done,
                                               # the loop stops only on budget / max-iters, advance tightens post-accept.
RATCHET_ADVANCE="${RATCHET_ADVANCE:-}"         # ratchet only: sibling script that tightens the baseline after an
                                               # accepted GREEN. Its own process; the runner never writes the baseline.
BUDGET_MIN="${BUDGET_MIN:-}"                   # wall-clock cap in minutes (hard stop, exit 6). Any shape; mainly for
                                               # ratchet/persistent loops that don't stop on GREEN. Empty => no cap.

log() { printf '%s  %s\n' "$(date -u +%FT%TZ)" "$*" | tee -a "$STATE_FILE" >&2; }
run_verifier() { bash "$VERIFIER"; }           # the ONLY thing that can declare success
run_maker()    { bash "$MAKER"; }              # the maker, as its own process (maker != checker)
now_ms() {                                     # epoch milliseconds, portably
  local ms; ms=$(date +%s%3N 2>/dev/null)
  case $ms in
    ''|*[!0-9]*) echo $(( $(date +%s) * 1000 ));;  # BSD/macOS date has no %N -> non-numeric; use seconds
    *) echo "$ms";;
  esac
}
iso_to_epoch() {                               # ISO-8601 UTC ("...Z") -> epoch seconds; "" if unparseable. Portable.
  local ts=$1 e
  if e=$(date -u -d "$ts" +%s 2>/dev/null); then printf '%s' "$e"; return 0; fi               # GNU date
  if e=$(date -u -j -f "%Y-%m-%dT%H:%M:%SZ" "$ts" +%s 2>/dev/null); then printf '%s' "$e"; return 0; fi  # BSD/macOS
  printf ''                                                                                    # neither parsed it
}
budget_exceeded() {                            # 0 (true) only when a wall-clock cap is set AND reached. Empty => never.
  [ -n "$BUDGET_MIN" ] || return 1
  local now elapsed_min
  now=$(date +%s)
  elapsed_min=$(( (now - BUDGET_START_EPOCH) / 60 ))
  [ "$elapsed_min" -ge "$BUDGET_MIN" ]         # BUDGET_MIN=0 => exceeded immediately
}
json_escape() { local s=${1//\\/\\\\}; s=${s//\"/\\\"}; printf '%s' "$s"; }

emit_metrics() { # iter wall_ms verifier_result accepted
  local iter=$1 wall=$2 res=$3 acc=$4 tokens=null cost=null out t c
  if [ -n "$METRICS_ADAPTER" ]; then
    out=$($METRICS_ADAPTER "$iter" 2>/dev/null || true)
    t=$(printf '%s' "$out" | awk '{print $1}'); c=$(printf '%s' "$out" | awk '{print $2}')
    [ -n "${t:-}" ] && [ "$t" != "-" ] && tokens=$t
    [ -n "${c:-}" ] && [ "$c" != "-" ] && cost=$c
  fi
  printf '{"iter":%s,"ts":"%s","wall_ms":%s,"verifier_result":"%s","accepted":%s,"tokens":%s,"cost_usd":%s}\n' \
    "$iter" "$(date -u +%FT%TZ)" "$wall" "$res" "$acc" "$tokens" "$cost" >> "$METRICS_FILE"
}
emit_checkpoint() { # iter verifier_result note
  printf '{"iter":%s,"ts":"%s","verifier_result":"%s","note":"%s"}\n' \
    "$1" "$(date -u +%FT%TZ)" "$2" "$(json_escape "$3")" >> "$STATE_JSONL"
}

# ---- --check preflight (m5): confirm both gates are runnable; make NO changes -
if [ "${1:-}" = "--check" ] || [ "${1:-}" = "--check-verifier" ]; then
  rc=0
  checks=("$VERIFIER" "$MAKER")
  # Under ratchet, the advance script is a load-bearing 3rd role — preflight it too (BUG-G).
  # If the shape is ratchet but no advance is wired, the baseline can never tighten — warn rather than pass silently.
  if [ "$VERIFIER_SHAPE" = ratchet ]; then
    if [ -n "$RATCHET_ADVANCE" ]; then checks+=("$RATCHET_ADVANCE")
    else echo "WARNING: VERIFIER_SHAPE=ratchet but RATCHET_ADVANCE is unset — the baseline will never tighten." >&2; fi
  fi
  for s in "${checks[@]}"; do
    if [ ! -f "$s" ]; then echo "MISSING: $s" >&2; rc=1; continue; fi
    if ! bash -n "$s" 2>/dev/null; then echo "NOT RUNNABLE: $s (syntax error)" >&2; rc=1; continue; fi
    echo "ok: $s present and parses" >&2
  done
  if bash "$VERIFIER" >/dev/null 2>&1; then
    echo "verify.sh executed -> GREEN" >&2
  elif [ "$?" -le 125 ]; then
    echo "verify.sh executed -> RED (a real verdict; fine for a smoke-check)" >&2
  else
    echo "verify.sh FAILED TO EXECUTE (exit >125 — not found / not a program)" >&2; rc=1
  fi
  exit $rc
fi

# ---- the loop ----------------------------------------------------------------
iter=0
if [ "${1:-}" = "--resume" ] && [ -f "$METRICS_FILE" ]; then
  iter=$(grep -c '"iter"' "$METRICS_FILE" 2>/dev/null || true)
  log "RESUME from iter $iter (per $METRICS_FILE)"
fi

# Wall-clock budget anchor — computed ONCE, resume-safe (BUG-C). If metrics already exist, measure elapsed from
# the FIRST recorded ts so --resume enforces a CUMULATIVE cap (not a fresh window per process); else from now.
# Always assigned (defaults to now) so `set -u` never trips even when the ts is missing/unparseable.
BUDGET_START_EPOCH=$(date +%s)
if [ -s "$METRICS_FILE" ]; then
  _first_ts=$(sed -n '1p' "$METRICS_FILE" 2>/dev/null | sed -n 's/.*"ts":[[:space:]]*"\([^"]*\)".*/\1/p')
  if [ -n "$_first_ts" ]; then
    _ep=$(iso_to_epoch "$_first_ts")
    [ -n "$_ep" ] && BUDGET_START_EPOCH=$_ep
  fi
fi

log "START goal=\"$GOAL\" max_iters=$MAX_ITERS autonomy=$AUTONOMY checkpoint_mode=$CHECKPOINT_MODE"

# A ratchet with no advance step never tightens the baseline — it just burns budget (a no-op loop). That silent
# no-op is exactly the failure LoopPrint exists to prevent, so surface it loudly at the start (don't fail: an
# unwired ratchet can be intentional mid-setup).
if [ "$VERIFIER_SHAPE" = ratchet ] && [ -z "$RATCHET_ADVANCE" ]; then
  log "WARNING: VERIFIER_SHAPE=ratchet but RATCHET_ADVANCE is unset — the baseline will never tighten (no-op ratchet)."
fi

# checkpoint autonomy needs an interactive terminal; refuse rather than hang/exit silently in CI.
if [ "$AUTONOMY" = "checkpoint" ] && [ ! -t 0 ]; then
  log "ERROR: autonomy=checkpoint needs a TTY, but stdin is not interactive (e.g. CI). Set AUTONOMY=full to run unattended."
  exit 5
fi

# Mark this run as live so `loopprint ls` won't misread an in-progress RED streak as ROTTEN.
# The trap clears it on any exit (normal, GREEN, max-iters, HALT, signal).
: > "$RUN_LOCK"
trap 'rm -f "$RUN_LOCK"' EXIT INT TERM

# Wall-clock budget is a HARD cap — check before any work so BUDGET_MIN=0 or a resumed over-budget run
# stops cleanly (exit 6) without burning an iteration. No-op for gate / unset budget.
if budget_exceeded; then log "STOP: wall-clock budget ${BUDGET_MIN}m reached."; exit 6; fi

# Verify-first (gate only): if the goal is already met, do nothing. A ratchet never early-exits on GREEN
# (GREEN means "no worse than baseline", not "done") — it skips this and falls into the loop.
if [ "$VERIFIER_SHAPE" != ratchet ] && run_verifier; then
  log "GREEN at iter $iter — nothing to do."
  emit_metrics "$iter" 0 GREEN true; emit_checkpoint "$iter" GREEN "already green at start"
  exit 0
fi

while :; do
  [ -f "$HALT_FILE" ] && { log "HALT file present — stopping."; exit 3; }
  if budget_exceeded; then log "STOP: wall-clock budget ${BUDGET_MIN}m reached."; exit 6; fi
  iter=$((iter + 1))
  if [ "$iter" -gt "$MAX_ITERS" ]; then
    if [ "$VERIFIER_SHAPE" = ratchet ]; then log "STOP: hit max_iterations ($MAX_ITERS) — ratchet stop reached."
    else log "STOP: hit max_iterations ($MAX_ITERS) without GREEN."; fi
    exit 2
  fi
  log "--- iteration $iter ---"

  # checkpoint BEFORE = authorize the iteration up front.
  if [ "$AUTONOMY" = "checkpoint" ] && [ "$CHECKPOINT_MODE" = "before" ]; then
    read -r -p "Authorize iteration $iter? [y/N] " ok || ok=n
    [ "$ok" = "y" ] || { log "User declined at pre-checkpoint."; exit 4; }
  fi
  if [ "$AUTONOMY" = "dry-run" ]; then
    log "DRY-RUN: would run $MAKER; skipping."; emit_metrics "$iter" 0 SKIP false; exit 0
  fi

  t0=$(now_ms)
  run_maker || log "maker step returned non-zero (continuing to verify)."

  # External verifier — the ONLY thing that can declare success. Maker != checker.
  if run_verifier; then res=GREEN; else res=RED; fi
  wall=$(( $(now_ms) - t0 ))

  accepted=false
  if [ "$res" = GREEN ]; then
    accepted=true
    # checkpoint AFTER = a human reviews the GREEN change and may reject it.
    if [ "$AUTONOMY" = "checkpoint" ] && [ "$CHECKPOINT_MODE" = "after" ]; then
      read -r -p "Iteration $iter is GREEN. Accept the change? [y/N] " ok || ok=n
      [ "$ok" = "y" ] || { accepted=false; log "Human rejected the GREEN change at post-checkpoint."; }
    fi
  fi

  # Ratchet advance (3rd role) — ONE place, post-accept, BEFORE emit_metrics so a failed advance demotes
  # 'accepted' in the recorded row (honest audit, BUG-A/F). Separate process; the runner never writes baseline.
  if [ "$VERIFIER_SHAPE" = ratchet ] && [ "$res" = GREEN ] && [ "$accepted" = true ] && [ -n "$RATCHET_ADVANCE" ]; then
    if ! bash "$RATCHET_ADVANCE"; then
      accepted=false
      log "ratchet-advance failed at iter $iter — marking not-accepted."
    fi
  fi

  emit_metrics "$iter" "$wall" "$res" "$accepted"
  emit_checkpoint "$iter" "$res" "iteration $iter -> $res (accepted=$accepted)"

  if [ "$VERIFIER_SHAPE" = ratchet ]; then
    # Ratchet: GREEN means "no worse than baseline", NOT "done" — never exit 0 here. A ratchet stops only on
    # budget or max-iters; the committed baseline (tightened post-accept) is the durable progress record.
    if [ "$res" = GREEN ]; then
      log "GREEN at iter $iter — not worse than baseline; continuing."
    else
      log "RED at iter $iter — verifier rejected; iterating."
    fi
  elif [ "$res" = GREEN ] && [ "$accepted" = true ]; then
    log "GREEN at iter $iter — goal met and change accepted. DONE."
    exit 0
  elif [ "$res" = GREEN ]; then
    log "GREEN but change rejected at post-checkpoint — iterating."
  else
    log "RED at iter $iter — verifier rejected; iterating."
  fi
done
