#!/usr/bin/env bash
# run-this-loop.sh — engine-agnostic loop runner generated by LoopPrint.
#
# Implements the four atoms literally:
#   Goal      — stated once in loop-spec.yaml; this runner does not re-derive it.
#   State     — appended to $STATE_FILE (human view) and $STATE_JSONL (append-only machine checkpoint) each iter.
#   Verifier  — $VERIFIER (default verify.sh), run as a SEPARATE process; exit 0 = GREEN. EXTERNAL by construction.
#   Stop      — whichever hits first: GREEN+accepted, $MAX_ITERS, or the HALT file.
#
# The MAKER is also a separate process ($MAKER, default maker.sh) — maker != checker, enforced structurally.
# This runner NEVER eval's a command string from the spec (see SECURITY.md): it execs sibling scripts only.
#
# Usage:
#   bash run-this-loop.sh            # run the loop
#   bash run-this-loop.sh --check    # preflight: confirm verify.sh + maker.sh are runnable; change nothing
#   bash run-this-loop.sh --resume   # continue the iteration count from $METRICS_FILE
set -euo pipefail

# ---- the four atoms (filled by LoopPrint from loop-spec.yaml) ----------------
GOAL="${GOAL:-<one-sentence goal>}"
STATE_FILE="${STATE_FILE:-state.md}"
STATE_JSONL="${STATE_JSONL:-state.jsonl}"      # append-only machine checkpoint (state.md is the human view)
VERIFIER="${VERIFIER:-verify.sh}"              # external gate: exits 0 = GREEN. Its own process.
MAKER="${MAKER:-maker.sh}"                      # the maker step: one change toward the goal. Its own process.
MAX_ITERS="${MAX_ITERS:-10}"
HALT_FILE="${HALT_FILE:-HALT}"
AUTONOMY="${AUTONOMY:-checkpoint}"             # full | checkpoint | dry-run
CHECKPOINT_MODE="${CHECKPOINT_MODE:-before}"   # before = authorize each iteration; after = review each result
METRICS_FILE="${METRICS_FILE:-metrics.jsonl}"  # append-only per-iteration metrics; feeds loopprint-report.py
METRICS_ADAPTER="${METRICS_ADAPTER:-}"         # optional cmd: prints "<tokens> <cost_usd>" for an iteration
                                               # (harness-specific). Core stays dep-free; tokens/cost are
                                               # INJECTED here, never parsed from the spec. Empty => null/null.

log() { printf '%s  %s\n' "$(date -u +%FT%TZ)" "$*" | tee -a "$STATE_FILE" >&2; }
run_verifier() { bash "$VERIFIER"; }           # the ONLY thing that can declare success
run_maker()    { bash "$MAKER"; }              # the maker, as its own process (maker != checker)
now_ms() {                                     # epoch milliseconds, portably
  local ms; ms=$(date +%s%3N 2>/dev/null)
  case $ms in
    ''|*[!0-9]*) echo $(( $(date +%s) * 1000 ));;  # BSD/macOS date has no %N -> non-numeric; use seconds
    *) echo "$ms";;
  esac
}
json_escape() { local s=${1//\\/\\\\}; s=${s//\"/\\\"}; printf '%s' "$s"; }

emit_metrics() { # iter wall_ms verifier_result accepted
  local iter=$1 wall=$2 res=$3 acc=$4 tokens=null cost=null out t c
  if [ -n "$METRICS_ADAPTER" ]; then
    out=$($METRICS_ADAPTER "$iter" 2>/dev/null || true)
    t=$(printf '%s' "$out" | awk '{print $1}'); c=$(printf '%s' "$out" | awk '{print $2}')
    [ -n "${t:-}" ] && [ "$t" != "-" ] && tokens=$t
    [ -n "${c:-}" ] && [ "$c" != "-" ] && cost=$c
  fi
  printf '{"iter":%s,"ts":"%s","wall_ms":%s,"verifier_result":"%s","accepted":%s,"tokens":%s,"cost_usd":%s}\n' \
    "$iter" "$(date -u +%FT%TZ)" "$wall" "$res" "$acc" "$tokens" "$cost" >> "$METRICS_FILE"
}
emit_checkpoint() { # iter verifier_result note
  printf '{"iter":%s,"ts":"%s","verifier_result":"%s","note":"%s"}\n' \
    "$1" "$(date -u +%FT%TZ)" "$2" "$(json_escape "$3")" >> "$STATE_JSONL"
}

# ---- --check preflight (m5): confirm both gates are runnable; make NO changes -
if [ "${1:-}" = "--check" ] || [ "${1:-}" = "--check-verifier" ]; then
  rc=0
  for s in "$VERIFIER" "$MAKER"; do
    if [ ! -f "$s" ]; then echo "MISSING: $s" >&2; rc=1; continue; fi
    if ! bash -n "$s" 2>/dev/null; then echo "NOT RUNNABLE: $s (syntax error)" >&2; rc=1; continue; fi
    echo "ok: $s present and parses" >&2
  done
  if bash "$VERIFIER" >/dev/null 2>&1; then
    echo "verify.sh executed -> GREEN" >&2
  elif [ "$?" -le 125 ]; then
    echo "verify.sh executed -> RED (a real verdict; fine for a smoke-check)" >&2
  else
    echo "verify.sh FAILED TO EXECUTE (exit >125 — not found / not a program)" >&2; rc=1
  fi
  exit $rc
fi

# ---- the loop ----------------------------------------------------------------
iter=0
if [ "${1:-}" = "--resume" ] && [ -f "$METRICS_FILE" ]; then
  iter=$(grep -c '"iter"' "$METRICS_FILE" 2>/dev/null || true)
  log "RESUME from iter $iter (per $METRICS_FILE)"
fi

log "START goal=\"$GOAL\" max_iters=$MAX_ITERS autonomy=$AUTONOMY checkpoint_mode=$CHECKPOINT_MODE"

# checkpoint autonomy needs an interactive terminal; refuse rather than hang/exit silently in CI.
if [ "$AUTONOMY" = "checkpoint" ] && [ ! -t 0 ]; then
  log "ERROR: autonomy=checkpoint needs a TTY, but stdin is not interactive (e.g. CI). Set AUTONOMY=full to run unattended."
  exit 5
fi

# Verify-first: if the goal is already met, do nothing.
if run_verifier; then
  log "GREEN at iter $iter — nothing to do."
  emit_metrics "$iter" 0 GREEN true; emit_checkpoint "$iter" GREEN "already green at start"
  exit 0
fi

while :; do
  [ -f "$HALT_FILE" ] && { log "HALT file present — stopping."; exit 3; }
  iter=$((iter + 1))
  if [ "$iter" -gt "$MAX_ITERS" ]; then log "STOP: hit max_iterations ($MAX_ITERS) without GREEN."; exit 2; fi
  log "--- iteration $iter ---"

  # checkpoint BEFORE = authorize the iteration up front.
  if [ "$AUTONOMY" = "checkpoint" ] && [ "$CHECKPOINT_MODE" = "before" ]; then
    read -r -p "Authorize iteration $iter? [y/N] " ok || ok=n
    [ "$ok" = "y" ] || { log "User declined at pre-checkpoint."; exit 4; }
  fi
  if [ "$AUTONOMY" = "dry-run" ]; then
    log "DRY-RUN: would run $MAKER; skipping."; emit_metrics "$iter" 0 SKIP false; exit 0
  fi

  t0=$(now_ms)
  run_maker || log "maker step returned non-zero (continuing to verify)."

  # External verifier — the ONLY thing that can declare success. Maker != checker.
  if run_verifier; then res=GREEN; else res=RED; fi
  wall=$(( $(now_ms) - t0 ))

  accepted=false
  if [ "$res" = GREEN ]; then
    accepted=true
    # checkpoint AFTER = a human reviews the GREEN change and may reject it.
    if [ "$AUTONOMY" = "checkpoint" ] && [ "$CHECKPOINT_MODE" = "after" ]; then
      read -r -p "Iteration $iter is GREEN. Accept the change? [y/N] " ok || ok=n
      [ "$ok" = "y" ] || { accepted=false; log "Human rejected the GREEN change at post-checkpoint."; }
    fi
  fi

  emit_metrics "$iter" "$wall" "$res" "$accepted"
  emit_checkpoint "$iter" "$res" "iteration $iter -> $res (accepted=$accepted)"

  if [ "$res" = GREEN ] && [ "$accepted" = true ]; then
    log "GREEN at iter $iter — goal met and change accepted. DONE."
    exit 0
  elif [ "$res" = GREEN ]; then
    log "GREEN but change rejected at post-checkpoint — iterating."
  else
    log "RED at iter $iter — verifier rejected; iterating."
  fi
done
