#!/usr/bin/env python3
"""loopprint-skillify — promote a GREEN loop directory into a reusable Agent Skill scaffold.

Step 6's "Save as skill": lint-gate first (maker != checker), then emit SKILL.md that documents
the loop's components — not a persona.

Usage:
    loopprint-skillify.py [--write] <loop-dir>

    <loop-dir> must contain loop-spec.yaml.

    Default (--dry-run): print SKILL.md to stdout.
    --write: write SKILL.md into <loop-dir>/.

Exit code:
    0  success
    1  refusal (lint RED, or emitted content violates the persona guard)
    2  usage error

Requires PyYAML (`pip install pyyaml`). Stdlib + PyYAML only; no network.
"""
from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    print("loopprint-skillify: PyYAML required (pip install pyyaml)", file=sys.stderr)
    sys.exit(2)

# LoopPrint invariant (ii): promoted skills document components, never a personality.
# The emitted SKILL.md must not contain persona/banner/governs-all-activity/confirmation language.
FORBIDDEN_SKILL_PHRASES = re.compile(
    r"\b(persona|banner|governs\s+all\s+activity|confirmation[-\s]?incantation|confirmation\s+phrase)\b",
    re.I,
)


def _load_lint_spec():
    lint_path = Path(__file__).resolve().parent / "loopprint-lint.py"
    spec = importlib.util.spec_from_file_location("loopprint_lint", lint_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load lint module from {lint_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.lint_spec


def _one_line(text: object) -> str:
    if text is None:
        return ""
    return " ".join(str(text).split())


def _yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _format_budget(budget: dict) -> str:
    if not isinstance(budget, dict):
        return "none"
    parts: list[str] = []
    for key in ("tokens", "wall_clock_minutes"):
        val = budget.get(key)
        if val is not None and str(val).strip().lower() not in ("", "null"):
            parts.append(f"{key}: {val}")
    return ", ".join(parts) if parts else "none"


def _format_stop(stop: dict) -> str:
    if not isinstance(stop, dict):
        stop = {}
    lines = [
        f"- **Success:** {_one_line(stop.get('success')) or '(not specified)'}",
        f"- **Max iterations:** {stop.get('max_iterations', '(not specified)')}",
        f"- **Budget:** {_format_budget(stop.get('budget', {}))}",
        f"- **Halt file:** {_one_line(stop.get('halt_file')) or '(not specified)'}",
    ]
    return "\n".join(lines)


def _format_verifier(verifier: dict) -> str:
    if not isinstance(verifier, dict):
        verifier = {}
    lines: list[str] = []
    cmd = verifier.get("command")
    if cmd is not None and str(cmd).strip():
        lines.append(f"- **Command:** `{_one_line(cmd)}`")
    reviewer = verifier.get("reviewer")
    if reviewer is not None and str(reviewer).strip():
        lines.append(f"- **Reviewer:** {_one_line(reviewer)}")
    green = _one_line(verifier.get("green_means"))
    lines.append(f"- **GREEN means:** {green or '(not specified)'}")
    return "\n".join(lines)


def build_skill_md(spec: dict, slug: str) -> str:
    goal = _one_line(spec.get("goal"))
    pattern = _one_line(spec.get("pattern")) or "(not specified)"
    description = f"{goal} Generated by LoopPrint from a verified loop."

    body = f"""# Loop: {slug}

Reusable loop blueprint promoted from a lint-GREEN `loop-spec.yaml`. This skill documents the
loop's atoms, verifier, and stop conditions.

## Goal

{goal or '(not specified)'}

## Pattern

{pattern}

## Verifier

{_format_verifier(spec.get("verifier", {}))}

## Stop conditions

{_format_stop(spec.get("stop", {}))}

## How to run

1. Review `loop-spec.yaml` and `safety-checklist.md` in this directory.
2. Execute `./run-this-loop.sh` to drive iterations.
3. The external gate is `./verify.sh` — exit 0 means GREEN; non-zero means RED.
"""
    frontmatter = (
        "---\n"
        f"name: loop-{slug}\n"
        f"description: {_yaml_quote(description)}\n"
        "license: MIT\n"
        "---\n"
    )
    return frontmatter + "\n" + body


def _guard_skill_content(content: str) -> list[str]:
    """Refuse promotion if the scaffold would violate the no-persona invariant."""
    findings: list[str] = []
    for match in FORBIDDEN_SKILL_PHRASES.finditer(content):
        findings.append(
            f"persona guard: emitted SKILL.md contains forbidden phrase '{match.group(0)}' "
            "(skills document components, not personalities)."
        )
    return findings


def main(argv: list[str]) -> int:
    args = [a for a in argv[1:] if a]
    write = False
    if "--write" in args:
        write = True
        args.remove("--write")
    if "--dry-run" in args:
        args.remove("--dry-run")

    if len(args) != 1:
        print(
            "usage: loopprint-skillify.py [--write] <loop-dir>\n"
            "       default: print SKILL.md to stdout; --write: write <loop-dir>/SKILL.md",
            file=sys.stderr,
        )
        return 2

    loop_dir = Path(args[0]).resolve()
    spec_path = loop_dir / "loop-spec.yaml"
    if not loop_dir.is_dir():
        print(f"loopprint-skillify: not a directory: {loop_dir}", file=sys.stderr)
        return 2
    if not spec_path.is_file():
        print(f"loopprint-skillify: missing {spec_path}", file=sys.stderr)
        return 2

    try:
        with open(spec_path) as fh:
            spec = yaml.safe_load(fh)
    except Exception as exc:
        print(f"loopprint-skillify: cannot read/parse {spec_path} ({exc})", file=sys.stderr)
        return 1

    if not isinstance(spec, dict):
        print(f"loopprint-skillify: {spec_path} is not a YAML mapping", file=sys.stderr)
        return 1

    try:
        lint_spec = _load_lint_spec()
    except Exception as exc:
        print(f"loopprint-skillify: cannot import lint gate ({exc})", file=sys.stderr)
        return 2

    findings = lint_spec(spec)
    if findings:
        print(f"REFUSE  {spec_path}: loop is not GREEN — fix before promoting to a skill.")
        for item in findings:
            print(f"   - {item}")
        return 1

    slug = _one_line(spec.get("slug")) or loop_dir.name
    if not slug:
        print("loopprint-skillify: cannot determine loop slug", file=sys.stderr)
        return 1

    content = build_skill_md(spec, slug)
    guard_findings = _guard_skill_content(content)
    if guard_findings:
        print("REFUSE  persona guard blocked promotion:")
        for item in guard_findings:
            print(f"   - {item}")
        return 1

    if write:
        out_path = loop_dir / "SKILL.md"
        out_path.write_text(content, encoding="utf-8")
        print(f"WROTE {out_path}")
    else:
        sys.stdout.write(content)
        if not content.endswith("\n"):
            sys.stdout.write("\n")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
